server:
  port: ${SERVER_PORT:8181}

spring:
  application:
    name: copilot-adapter
  cache:
    redis:
      time-to-live: 60m

copilot:
  token: ${GITHUB_COPILOT_TOKEN}
  api-url: ${COPILOT_API_URL:https://models.github.ai}
  version: ${COPILOT_API_VERSION:2026-03-10}

rest:
  client:
    request:
      interceptor:
        hidden-headers: authorization,content-security-policy,set-cookie
  service:
    request:
      hidden-headers: authorization

logging:
  level:
    com.legadi.openai.copilot: DEBUG
    org.springframework.web.filter: DEBUG
    org.springframework: INFO
